apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::975050082972:role/no-multus-nodegroup-stack-NodeGroupNodeGroupRole8FF-Zz3iZz0jTsdh
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::975050082972:role/pipeline-cdk-stack-CodeBuildRole728CBADE-rsxzdNdVfZcT
      username: CodeBuildRole
      groups:
        - system:masters
